// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "geometrydash ship":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
...............................................ffff.............
..............................................ff9fff............
.............................................fff99fff...........
.............................................f9f99faf...........
.............................................f9f99fafffff.......
.............................................f9f99faaffdff......
.........................................fffff9999fcaffdff......
.........................................f1fff9666ffcafddff.....
......fff............................fffff111ffffffffcafddff....
.......ffff..........................fccfff111fffaaaafcffddf....
........fffff........................ffcfaff11ffaaaaafffffdff...
..ffffffddf9ffff......................fcfaafffffffffaccccfddf...
...f999fddf99aaffff...................fcaaaafff999fffaaaacfdff..
....ff99fddf99aafffffff................ffaaaacf999ffffcaacfddf..
......f9fddff99aafffffffff..............ffffacf999ffcaaaafffff..
....fffffddfff99aaaa9f699fffffffffffff..ffcaacffffffcaaaaa9fff..
....fddffddfaff999a99f6fff66669999fffffffffaaafffffaaaaaaaa9ff..
.....fddfffaaafff9999f6fafffff999ffccfffaaaaaaaaaaaaaacccccc9f..
.....ffdddfcaaaaff99fffcaaaafff99faaccfffaffffffffffffffffffff..
......fdddfcccaaaafffffccaaffcffffaaacfcfaaf99999faaaaaaaacff...
...ffffffdaffcccaffcaaafcccfcaaaaffaacfccfaaf999faaaaaaaaccff...
....ffffffa99fffffccaaafffffffffaaffffaacfaaaf9faaaaaaaacfff....
.....ffffca999999ffcaaacfcf99996faaaaaafffffaafaaaaaaaacff......
......ffcca66669999fccccfacf666fccccaaff9ffffaaaaaaaacccf.......
.......cccaa6cccccfffffffaccf6faaaaaaaf99fffffaaaaaccfff........
.......ffffdaaaaaf96caaffacccfffffffaaffff99fffaacccff..........
......ffffff999fff96caaafcaaaacf666faccccf99fffccffff...........
....fff669999aaf996fcaaffffffff6999fccffffffffffff..............
...fff6ccccaaaf9966fcfff66666ff6999ffffddff.....................
..ffffccaaaaff9966fffff669996fffffffddddff......................
.....ffffffdddf6699faaf69fffffffdddddffff.......................
........fddddf66999fffffffdddddddfffff..........................
........fddfff6699fffdddddddddffff..............................
.......fffff.f666ffdddddddfffff.................................
.............fffffddfffffff.....................................
................fffff...........................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
